/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Septiancesare
 */
public class frameMenu extends javax.swing.JFrame {

    /**
     * Creates new form frameMenu
     */
    public frameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAnggota = new javax.swing.JButton();
        btnPeminjaman = new javax.swing.JButton();
        btnPengembalian = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnBuku = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnggota.setBackground(new java.awt.Color(251, 205, 31));
        btnAnggota.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        btnAnggota.setForeground(new java.awt.Color(125, 39, 34));
        btnAnggota.setText("Data Anggota");
        btnAnggota.setBorder(null);
        btnAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 300, 170));

        btnPeminjaman.setBackground(new java.awt.Color(251, 205, 31));
        btnPeminjaman.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        btnPeminjaman.setForeground(new java.awt.Color(125, 39, 34));
        btnPeminjaman.setText("Peminjaman Buku");
        btnPeminjaman.setBorder(null);
        btnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 300, 180));

        btnPengembalian.setBackground(new java.awt.Color(251, 205, 31));
        btnPengembalian.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        btnPengembalian.setForeground(new java.awt.Color(125, 39, 34));
        btnPengembalian.setText("Pengembalian Buku");
        btnPengembalian.setBorder(null);
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 310, 170));

        btnAdmin.setBackground(new java.awt.Color(251, 205, 31));
        btnAdmin.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(125, 39, 34));
        btnAdmin.setText("Data Admin");
        btnAdmin.setBorder(null);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 300, 180));

        btnBuku.setBackground(new java.awt.Color(251, 205, 31));
        btnBuku.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        btnBuku.setForeground(new java.awt.Color(125, 39, 34));
        btnBuku.setText("Data  Buku");
        btnBuku.setBorder(null);
        btnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 310, 180));

        btnKeluar.setBackground(new java.awt.Color(251, 205, 31));
        btnKeluar.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(125, 39, 34));
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(null);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 310, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MENU.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
        // TODO add your handling code here:
        framePengembalian pengembalian = new framePengembalian();
        pengembalian.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnPengembalianActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        frameLogin login = new frameLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnggotaActionPerformed
        // TODO add your handling code here:
        frameAnggota anggota = new frameAnggota();
        anggota.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnAnggotaActionPerformed

    private void btnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeminjamanActionPerformed
        // TODO add your handling code here:
        framePeminjaman peminjaman = new framePeminjaman();
        peminjaman.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnPeminjamanActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        frameDataAdmin admin = new frameDataAdmin();
        admin.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed
        // TODO add your handling code here:
        frameBuku buku = new frameBuku();
        buku.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAnggota;
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
