/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import com.mycompany.projectperpus.ConnectionDatabase;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Septiancesare
 */
public class framePengembalian extends javax.swing.JFrame {

    /**
     * Creates new form framePengembalian
     */
    private DefaultTableModel tableModel;
    
    public framePengembalian() {
        initComponents();
        
        tableModel = (DefaultTableModel) tabelPengembalian.getModel();

        // Inisialisasi Timer untuk polling data setiap 5 detik (sesuai kebutuhan)
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                refreshTableData();
            }
        });
        timer.start();

        // Panggil metode pertama kali untuk mengisi data tabel
        refreshTableData();
    }
    
   private void refreshTableData() {
        try {
            ConnectionDatabase koneksidatabase = ConnectionDatabase.getInstance();
            Connection connect = koneksidatabase.getConnection();

            // Mengambil data dari database
            String query = "SELECT * FROM pengembalian";
            try (PreparedStatement statement = connect.prepareStatement(query);
                 ResultSet resultSet = statement.executeQuery()) {

                // Clear existing data
                tableModel.setRowCount(0);

                // Populate data from the result set
                ResultSetMetaData metaData = resultSet.getMetaData();
                int columnCount = metaData.getColumnCount();

                // Add rows to the model
                while (resultSet.next()) {
                    Object[] row = new Object[columnCount];
                    for (int i = 1; i <= columnCount; i++) {
                        row[i - 1] = resultSet.getObject(i);
                    }
                    tableModel.addRow(row);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputNoUrut = new javax.swing.JTextField();
        inputIdPetugas = new javax.swing.JTextField();
        inputIdAnggota = new javax.swing.JTextField();
        inputNamaAnggota = new javax.swing.JTextField();
        inputIdBuku = new javax.swing.JTextField();
        inputJudulBuku = new javax.swing.JTextField();
        TanggalKembali = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPengembalian = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputNoUrut.setBackground(new java.awt.Color(222, 217, 186));
        inputNoUrut.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        inputNoUrut.setForeground(new java.awt.Color(125, 39, 34));
        inputNoUrut.setBorder(null);
        jPanel1.add(inputNoUrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 410, 40));

        inputIdPetugas.setBackground(new java.awt.Color(222, 217, 186));
        inputIdPetugas.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        inputIdPetugas.setForeground(new java.awt.Color(125, 39, 34));
        inputIdPetugas.setBorder(null);
        jPanel1.add(inputIdPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 410, 30));

        inputIdAnggota.setBackground(new java.awt.Color(222, 217, 186));
        inputIdAnggota.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        inputIdAnggota.setForeground(new java.awt.Color(125, 39, 34));
        inputIdAnggota.setBorder(null);
        jPanel1.add(inputIdAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 410, 30));

        inputNamaAnggota.setBackground(new java.awt.Color(222, 217, 186));
        inputNamaAnggota.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        inputNamaAnggota.setForeground(new java.awt.Color(125, 39, 34));
        inputNamaAnggota.setBorder(null);
        jPanel1.add(inputNamaAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 410, 30));

        inputIdBuku.setBackground(new java.awt.Color(222, 217, 186));
        inputIdBuku.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        inputIdBuku.setForeground(new java.awt.Color(125, 39, 34));
        inputIdBuku.setBorder(null);
        jPanel1.add(inputIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 410, 30));

        inputJudulBuku.setBackground(new java.awt.Color(222, 217, 186));
        inputJudulBuku.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        inputJudulBuku.setForeground(new java.awt.Color(125, 39, 34));
        inputJudulBuku.setBorder(null);
        jPanel1.add(inputJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 410, 30));

        TanggalKembali.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        TanggalKembali.setForeground(new java.awt.Color(125, 39, 34));
        jPanel1.add(TanggalKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 410, 30));

        btnTambah.setBackground(new java.awt.Color(125, 39, 34));
        btnTambah.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(222, 217, 186));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(null);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, 210, 40));

        btnUbah.setBackground(new java.awt.Color(125, 39, 34));
        btnUbah.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(222, 217, 186));
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, 210, 40));

        btnHapus.setBackground(new java.awt.Color(125, 39, 34));
        btnHapus.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(222, 217, 186));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 210, 40));

        btnKeluar.setBackground(new java.awt.Color(125, 39, 34));
        btnKeluar.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(222, 217, 186));
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(null);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 323, 210, 40));

        tabelPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Anggota", "Nama Anggota", "ID Buku", "Judul Buku", "ID Petugas", "Tanggal Pengembalian", "Denda", "ID Pinjam", "ID Kembali", "Jatuh Tempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPengembalian);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 477, 1300, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DATA PENGEMBALIAN.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        LocalDateTime currentime = LocalDateTime.now();
                
        DateTimeFormatter formatt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String tanggalSekarang = currentime.format(formatt);
        TanggalKembali.setText(tanggalSekarang);
         
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        frameMenu menu = new frameMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tabelPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPengembalianMouseClicked
        // TODO add your handling code here:
        
        try {
            ConnectionDatabase koneksidatabase;
            koneksidatabase = ConnectionDatabase.getInstance();
            Connection connect = koneksidatabase.getConnection();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(framePengembalian.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        int row = tabelPengembalian.getSelectedRow();
        
//        if (row == -1){
//            return;
//        
//        }
        

        String idPinjam = (String) tabelPengembalian.getValueAt(row, 1);
        inputNoUrut.setText(idPinjam);
        
        String idPetugas = (String) tabelPengembalian.getValueAt(row, 6);
        inputIdPetugas.setText(idPetugas);
        
        String idAnggota = (String) tabelPengembalian.getValueAt(row, 3);
        inputIdAnggota.setText(idAnggota);
        
        String namaAnggota = (String) tabelPengembalian.getValueAt(row, 4);
        inputNamaAnggota.setText(namaAnggota);
        
        String idBuku = (String) tabelPengembalian.getValueAt(row, 5);
        inputIdBuku.setText(idBuku);
        
        String judulBuku = (String) tabelPengembalian.getValueAt(row, 9);
        inputJudulBuku.setText(judulBuku);
        
    }//GEN-LAST:event_tabelPengembalianMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePengembalian().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TanggalKembali;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputIdAnggota;
    private javax.swing.JTextField inputIdBuku;
    private javax.swing.JTextField inputIdPetugas;
    private javax.swing.JTextField inputJudulBuku;
    private javax.swing.JTextField inputNamaAnggota;
    private javax.swing.JTextField inputNoUrut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPengembalian;
    // End of variables declaration//GEN-END:variables
}
